version: '3.3'

volumes:
  postgres_data_prod:
  traefik-public-certificates:


services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: 'gunicorn --bind 0.0.0.0:8000 config.wsgi'
    expose:
      - 8000
    env_file:
      - app/.env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`dimitriovski.com`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - app/.env

  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
