# docker-compose.yml

version: '3.3'

services:
  web:
    build: ./app
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app:/app
    expose:
      - 8000
    env_file:
      - app/.env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`django.localhost`)"
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - app/.env
  traefik:
    image: traefik:v2.2
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  postgres_data:
